spring:
  #activiti使用数据源
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/spring_activiti_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        username: root
        password: 123456
        continue-on-error: false
        initialize: false
        data: classpath:data.sql
  activiti:
    #异步执行器激活
    async-executor-activate: false
    #启动是否检查流程xml定义,默认后缀为**.bpmn,**.bpmn20.xml
    check-process-definitions: true
    process-definition-location-prefix: classpath:/processes/
    #process-definition-location-suffixes:
    #启动时初始化activiti数据库表
    database-schema: spring_activiti_demo
    database-schema-update: true
    db-history-used: true
    db-identity-used: true
    #是否启用restful接口,用于流程,任务,历史的查询,默认restful路径为/api/**
    #rest-api-enabled: true
    #rest-api-mapping:
    #rest-api-servlet-name:
    deployment-name:
    #历史记录级别,full为最高
    history-level: full
    jpa-enabled: true
    #mail-server-default-from:
    #mail-server-host:
    #mail-server-port:
    #mail-server-user-name:
    #mail-server-password:
    #mail-server-use-ssl: true
    #mail-server-use-tls: true

server:
  port: 80

logging:
  level:
    root: info